### ISSUE TITLE
Debian/Ubuntu APT dependencies

### ISSUE THREAD

**Issue by bsaid** [Tasssadar/Lorris#37]
lorris: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by lorris)
lorris: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by lorris)
lorris: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by lorris)
lorris: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by lorris)

**Comment by Tasssadar** [comment]
Check what's inside your APT source file, `/etc/apt/sources.list.d/lorris.list`, should look something like this:

> deb http://apt.tasemnice.eu/ubuntu *stable* main

The bold part specifies the Ubuntu release name, stable in this case in an alias for Focal Fossa (20.04). You probably have wrong release name in there, it should be the one that matches your Ubuntu version. The options are visible here in the directory listing: http://apt.tasemnice.eu/ubuntu/dists/

Ubuntu version name to number mapping is here: https://wiki.ubuntu.com/Releases

**Comment by bsaid** [comment]
Thank you. I confirm that this solved the issue.

> deb http://apt.tasemnice.eu/ubuntu bionic main
